name: Go

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - uses: actions/checkout@v2

      - name: Install libbcc
        run: |
          curl -sL https://github.com/cloudflare/ebpf_exporter/files/3890546/libbcc_0.11.0-2_amd64.deb.gz | gunzip > /tmp/libbcc.deb
          sudo dpkg -i /tmp/libbcc.deb
          rm /tmp/libbcc.deb

      - name: Check vendored dependencies
        run: |
          go mod verify

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
