name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - name: Install libbcc
        run: |
          curl -sL https://github.com/cloudflare/ebpf_exporter/files/3890546/libbcc_0.11.0-2_amd64.deb.gz | gunzip > /tmp/libbcc.deb
          sudo dpkg -i /tmp/libbcc.deb
          rm /tmp/libbcc.deb

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
